### ISSUE TITLE
怎么 public 的项目 readme 中的介绍反而是 private 的

### ISSUE THREAD

**Issue by Chen-RT** [NJUPT-SAST/sast-link#5]
前端真的不考虑封装些组件吗？👀

**Comment by Minngc** [comment]
首先非常感谢您能浏览该项目，关于您的疑惑：
Q: 介绍为 Private?
A：项目中的「介绍链接」指向 SAST 社团组织的开发文档。该项目最初为一人开发，起初并未发布规范的开发文档。目前的开发文档是为了方便组织人员接手文档而临时制作，并未考虑社区规范等。后续会对文档进行更新。
Q：封装组件？
A：项目初期确实有封装一些组件，不过目前项目仍在开发中，后续开发的组件并未封装，您可以期待之后的版本。

**Comment by Chen-RT** [comment]
> 首先非常感谢您能浏览该项目，关于您的疑惑： Q: 介绍为 Private? A：项目中的「介绍链接」指向 SAST 社团组织的开发文档。该项目最初为一人开发，起初并未发布规范的开发文档。目前的开发文档是为了方便组织人员接手文档而临时制作，并未考虑社区规范等。后续会对文档进行更新。 Q：封装组件？ A：项目初期确实有封装一些组件，不过目前项目仍在开发中，后续开发的组件并未封装，您可以期待之后的版本。

这么晚了还在看github太肝了。
封装组件的本意是指单独的组件库，不过确实，看起来sast的ui风格和前端框架一直在变也不太好封装

**Comment by Minngc** [comment]
睡前清邮件，看到了就顺着回了。
项目开启之初确实有设置组件库的打算，不过并没有推进。UI 风格不统一是一个问题，还有另外的问题是，我们目前都忙于学业与找工作等生活相关的事情，有些应接不暇，该项目实际也已经被搁置了一段时间。

**Comment by MaxtuneLee** [comment]
> > 首先非常感谢您能浏览该项目，关于您的疑惑： Q: 介绍为 Private? A：项目中的「介绍链接」指向 SAST 社团组织的开发文档。该项目最初为一人开发，起初并未发布规范的开发文档。目前的开发文档是为了方便组织人员接手文档而临时制作，并未考虑社区规范等。后续会对文档进行更新。 Q：封装组件？ A：项目初期确实有封装一些组件，不过目前项目仍在开发中，后续开发的组件并未封装，您可以期待之后的版本。
> 
> 这么晚了还在看github太肝了。 封装组件的本意是指单独的组件库，不过确实，看起来sast的ui风格和前端框架一直在变也不太好封装

目前已经在建立一个统一的设计系统和UI库，叫SAST UI，准备完毕之后就public到github这边，React版本的已经可以release了，web component版本还在开发中，主要是 @BQXBQX 同学在负责这块

**Comment by MaxtuneLee** [comment]
> > > 首先非常感谢您能浏览该项目，关于您的疑惑： Q: 介绍为 Private? A：项目中的「介绍链接」指向 SAST 社团组织的开发文档。该项目最初为一人开发，起初并未发布规范的开发文档。目前的开发文档是为了方便组织人员接手文档而临时制作，并未考虑社区规范等。后续会对文档进行更新。 Q：封装组件？ A：项目初期确实有封装一些组件，不过目前项目仍在开发中，后续开发的组件并未封装，您可以期待之后的版本。
> > 
> > 
> > 这么晚了还在看github太肝了。 封装组件的本意是指单独的组件库，不过确实，看起来sast的ui风格和前端框架一直在变也不太好封装
> 
> 目前已经在建立一个统一的设计系统和UI库，叫SAST UI，准备完毕之后就public到github这边，React版本的已经可以release了，web component版本还在开发中，主要是 @BQXBQX 同学在负责这块

欢迎关注 https://github.com/NJUPT-SAST/SAST-UI
